### ISSUE TITLE
Database connection with user credentials

### ISSUE THREAD

**Issue by Ndrou** [codemix/oriento#169]
Hi !

Is there any way to connect to a database without filling the server (root) credentials, but only with user database credentials ?

Thanks ;)

**Comment by rschmukler** [comment]
Any update on this or an estimate on when 2.0 will be done? Would you guys accept a PR before 2.0 lands adding this? Not sure if I'll have time, but figure I would ask!

Thanks for the great work!

**Comment by phpnode** [comment]
@rschmukler I actually think it should work as it is:
```js
var db = require('oriento'){).use({
  name: "dbname",
  username: "admin",
  password: "admin"
});

db.select().from('OUser').all().then(console.log.bind(console));
```

**Comment by phpnode** [comment]
(if it doesn't work, would definitely accept a PR for this in 1.x as 2.0 will take a while, but such a PR is unlikely to be trivial I think)

**Comment by rschmukler** [comment]
@phpnode thanks for the quick response. I tried that initially, and got the following error:

```
Unhandled rejection OrientDB.RequestError: Wrong user/password to [connect] to the remote OrientDB Server instance. Get the user/password from the config/orientdb-server-config.xml file
    at Operation.parseError (/Users/ryan/Dev/offmarket/seed/node_modules/oriento/lib/transport/binary/protocol19/operation.js:807:13)
    at Operation.consume (/Users/ryan/Dev/offmarket/seed/node_modules/oriento/lib/transport/binary/protocol19/operation.js:397:35)
    at Connection.process (/Users/ryan/Dev/offmarket/seed/node_modules/oriento/lib/transport/binary/connection.js:360:17)
    at Connection.handleSocketData (/Users/ryan/Dev/offmarket/seed/node_modules/oriento/lib/transport/binary/connection.js:279:17)
    at emitOne (events.js:75:13)
    at Socket.emit (events.js:150:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:109:10)
    at TCP.onread (net.js:510:20)
```

I took a poke around the code and it does indeed seem non-trivial. What is interesting is that [the docs on the operation](https://github.com/orientechnologies/orientdb/wiki/Network-Binary-Protocol#request_db_open) seem to specify that it should just work... Further more, the following does work from the console...

```
connect remote:localhost/dbname admin admin
```

**Comment by rschmukler** [comment]
Actually, I think I have an idea... stand by.

**Comment by Ndrou** [comment]
Good job guys ! ;)
