### ISSUE TITLE
"sql." is added in the begining of statements sent to the database

### ISSUE THREAD

**Issue by dharmax** [codemix/oriento#196]
Example:
```javascript
  db.let('firstVertex', function (s) {
                s.insert().into('NamedEntity')
                    .set({
                        formalName: name,
                        creationTime: Date.now(),
                        status: fields && fields.status || "Undecided"
                    });
            })
```
resulted in an exception:
```
Possibly unhandled OrientDB.RequestError: Error on execution of command: sql.INSERT INTO NameString SET string = "Mizrahi", language = "en"
    at Operation.parseError (/home/avit/development/backend.core.ontology/node_modules/oriento/lib/transport/binary/protocol28/operation.js:832:13)
    at Operation.consume (/home/avit/development/backend.core.ontology/node_modules/oriento/lib/transport/binary/protocol28/operation.js:422:35)
    at Connection.process (/home/avit/development/backend.core.ontology/node_modules/oriento/lib/transport/binary/connection.js:360:17)
    at Connection.handleSocketData (/home/avit/development/backend.core.ontology/node_modules/oriento/lib/transport/binary/connection.js:279:17)
    at Socket.emit (events.js:95:17)
    at Socket.stream.pause.paused (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
    at readableAddChunk (_stream_readable.js:165:9)

```

i didn't even find a string "sql." in oriento code....

**Comment by dharmax** [comment]
my mistake...
