### ISSUE TITLE
Param doesn't work with date() [v2.0.2]

### ISSUE THREAD

**Issue by dvine-multimedia** [codemix/oriento#287]
Hi phpnode.

I have a simple document class 'Message' with a datetime property named 'updated'.
The default datetime format of the db is 'yyyy-MM-dd HH:mm:ss.SSS'
In the following example DB holds the connection to the database.

This query works as expected:
DB.select()
    .from('Message')
    .where("updated > date( '2015-03-15 16:42:09.045' )")
    .all()
    .then(function(results){
        console.log(results);
    });

This one does crash:
DB.select()
    .from('Message')
    .where("updated > date( :updated )")
    .addParam('updated', '2015-03-15 16:42:09.045')
    .all()
    .then(function(results){
        console.log(results);
    });

**Comment by dmarcelino** [comment]
Hi @dvine-multimedia, I'm not sure why that fails, but the below workaround should work:
``` javascript
DB.select()
.from('Message')
.where("updated > date( :updated )")
.addParam('updated', new Date(2015, 3, 15, 16, 42, 9, 45))
.all()
.then(function(results){
console.log(results);
});
```

A working example:
https://github.com/codemix/oriento/blob/master/test/bugs/203-param-date.js

**Comment by dvine-multimedia** [comment]
Actually in my case it does not. Using OrientDb 2.0.5 on Windows for the above I get following exception:

2015-03-17 16:14:31:756 INFO  OrientDB Server v2.0.5 is active. [OServer]Sent run-time exception to the client /127.0.0.1:50841: com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.SELECT * FROM Message WHERE updated > date( :datex )
com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.SELECT * FROM Message WHERE updated > date( :datex )
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1195)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1178)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1178)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:385)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:220)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
Caused by: java.lang.ClassCastException: com.orientechnologies.orient.core.sql.filter.OSQLFilterItemParameter cannot be cast to java.lang.String
	at com.orientechnologies.orient.core.sql.functions.misc.OSQLFunctionDate.execute(OSQLFunctionDate.java:75)
	at com.orientechnologies.orient.core.sql.functions.OSQLFunctionRuntime.execute(OSQLFunctionRuntime.java:126)
	at com.orientechnologies.orient.core.sql.functions.OSQLFunctionRuntime.getValue(OSQLFunctionRuntime.java:142)
	at com.orientechnologies.orient.core.sql.OSQLHelper.getValue(OSQLHelper.java:231)
	at com.orientechnologies.orient.core.sql.OFilterAnalyzer.createIndexedProperty(OFilterAnalyzer.java:229)
	at com.orientechnologies.orient.core.sql.OFilterAnalyzer.analyzeIndexMethod(OFilterAnalyzer.java:154)
	at com.orientechnologies.orient.core.sql.OFilterAnalyzer.analyzeFilterBranch(OFilterAnalyzer.java:139)
	at com.orientechnologies.orient.core.sql.OFilterAnalyzer.analyzeCondition(OFilterAnalyzer.java:103)
	at com.orientechnologies.orient.core.sql.OFilterAnalyzer.analyzeOrFilterBranch(OFilterAnalyzer.java:84)
	at com.orientechnologies.orient.core.sql.OFilterAnalyzer.analyzeMainCondition(OFilterAnalyzer.java:58)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchForIndexes(OCommandExecutorSQLSelect.java:1453)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchInClasses(OCommandExecutorSQLSelect.java:764)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.assignTarget(OCommandExecutorSQLResultsetAbstract.java:194)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.assignTarget(OCommandExecutorSQLSelect.java:438)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:420)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:391)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1189)
	... 6 more

**Comment by dmarcelino** [comment]
Apologies @dvine-multimedia, my earlier example had a typo: `.where("updated > date( :updated )")`. I've amended it to `.where("updated > :updated")`.

**Comment by dvine-multimedia** [comment]
It works. I should have tried this before. Thanks a lot.

**Comment by dmarcelino** [comment]
No problem. :smiley:
